### ISSUE TITLE
linkToPod is missing

### ISSUE THREAD

**Issue by gmoduser38** [Fasteroid/expression2-public#4]
![image](https://github.com/Fasteroid/expression2-public/assets/134816662/520d93eb-f9de-4127-ab4d-0026ddc39b7c)

why does this happen

**Comment by Fasteroid** [comment]
Oh, right, forgot that function is only in antcore... I'll see about finding a workaround

**Comment by gmoduser38** [comment]
![image](https://github.com/Fasteroid/expression2-public/assets/134816662/4ec8e5a0-08b6-418f-b2bb-994c3ceaebf0)

installed the new fix and still getting the error, even installed antcore. weird
