### ISSUE TITLE
Turret module delta operator issue

### ISSUE THREAD

**Issue by gmoduser38** [Fasteroid/expression2-public#5]
![image](https://github.com/Fasteroid/expression2-public/assets/134816662/d4d15040-ed7f-4c2c-914c-20eaa0250b5b)

i fixed the other error by installing antcore, but now i get this error

**Comment by Fasteroid** [comment]
it's not a temporary variable tho... wtf is it on about?
edit: e2 is dumb, can you try swapping that line with the one below it and see what happens?

**Comment by gmoduser38** [comment]
i tried that and i'm still getting the error, i don't know why this happens even after swapping the lines.

**Comment by gmoduser38** [comment]
Hey, so the new version you recently uploaded fixes the error, but I keep getting this error:

![image](https://github.com/Fasteroid/expression2-public/assets/134816662/6b4db026-d40b-4434-b37e-a8bd7636df5a)

And when I disable antcore, this happens:

![image](https://github.com/Fasteroid/expression2-public/assets/134816662/64dabd57-6bad-4338-b9bd-148d1b3d3e8f)

Hopefully you can fix these, me and my friends have been waiting so we can play as Wrecking Ball, but we'll wait for now. Take your time.

**Comment by Fasteroid** [comment]
Gonna close this issue since you're addressing a new one now, but I'll do the decency of answering it here.

You absolutely need the "make spherical" addon for wrecking ball to work—at least for now.  Without it, rolling will be a bumpy ride and rather undesirable.

**Comment by replitidk** [comment]
@gmoduser38 Deltarade fixed this just do #ifdef makespherical(5)
#endif and just do the #ifdef (make spherical thing here) #endif on all the make spherical stuff in the code
