### ISSUE TITLE
Instability at low tick quota values

### ISSUE THREAD

**Issue by gmoduser38** [Fasteroid/expression2-public#8]
Whenever I spawn in Wrecking Ball, the mech randomly does the fireball effect and then when I get in the mech it just starts jumping weirdly and if I try to Piledrive then the Tick quota exceeded error happens.

**Comment by Fasteroid** [comment]
Sounds like the server tick quota is too low, which is weird because during testing it worked on a server with normal quota values.

Is `wire_expression2_quotatick` set to 10000 or higher?

**Comment by Fasteroid** [comment]
stale and couldn't reproduce
