### ISSUE TITLE
turret spawning issues 

### ISSUE THREAD

**Issue by replitidk** [Fasteroid/expression2-public#9]
When I spawn the mech (very cool mech, by the way), the turrets won't spawn. So, I grab the turret tool, and just as I spawn it, all the turrets go to the E2 rather than the turrets on the mech. I have zero idea if Deltarade told you about this, and I don't know if you know Deltarade since Delta said he knew you, but I have zero idea. I tried checking the code, but I am dumb and no E2 wizard, and can't find why it keeps sending the turrets to the E2 rather than the mech

**Comment by replitidk** [comment]
@Fasteroid

**Comment by Fasteroid** [comment]
If the turrets and cam controller aren't automatically spawning, **make sure you have concmd enabled**:
`wire_expression2_concmd 1`

As for why they aren't attaching to the hardpoints on the mech, I have no idea; I've never seen that happen before.
Unfortunately, unless I can reproduce it, I probably can't fix it.  What version of E2 Wrecking Ball are you on (make sure you're using the latest!), and do you have any convars related to E2 changed from their defaults?

**Comment by replitidk** [comment]
I have concmd on, and I am running the latest version. I will try to send a video of the issue, and I will also give the concmd in the little command line. I think the problem is E:entity:setpos(), and I forgot what was in the set pos, but since entity is the expression 2, I think it is just sending the turrets to the expression 2. A fix may be to use applyforce on the turrets and send them to the props around the turret, but I have zero idea. I will try to mess with the concmd and stuff and see if I can get it to work, but otherwise, I will just change the code so that way I can wire the turrets up to the e2 and use applyforce; otherwise, there is nothing we can really do.

**Comment by Fasteroid** [comment]
@replitidk, I appreciate your information so far, but I'd appreciate it even more if you could organize your thoughts more clearly.  Even with added punctuation from ChatGPT, your original run-on sentences are still really hard to understand for me.  

Also, you don't have to ping me—I see these in my email even if you don't 🙂 

With that out of the way... may I ask what server you're having problems on?  I'd much rather join and troubleshoot for myself so I can narrow down what might be going on.

**Comment by Fasteroid** [comment]
Nevermind, I got the server IP from DeltaRade.  Will reply shortly when I figure out how to reproduce your issue,

**Comment by Fasteroid** [comment]
Can't reproduce, likely user error.
Come find me on Discord if you need any more help.

**Comment by replitidk** [comment]
Ok thanks i will see if i can mod the code to try to jerry rig it up to the mech otherwise then I wont bother you any more thanks for the help and also still its a pretty cool mech.

**Comment by Fasteroid** [comment]
Don't modify the code, just enable concmd correctly.  It literally worked for Delta on the server you report it didn't work on.

**Comment by replitidk** [comment]
I have concmd on and +attack, -attack, in concmd line for it but the issue is that the turrets spawn but keep going to the e2 and not the mech so if i cant get how it was supposed to work to you know work then i will just jerry rig it to the mech

**Comment by Fasteroid** [comment]
Locking this so it stops getting used like a Discord channel.
